export default {
  yAxisWidth: 15,
  yAxisSplit: 5,
  yAxisTitleWidth: 15,
  xAxisHeight: 13,
  xAxisLineHeight: 2,
  xAxisTextPadding: 5,
  xAxisLabelFontNumber: 1.5,
  legend: true,
  legendHeight: 15,
  padding: 10,
  columePadding: 5,
  fontSize: 10,
  xAxisFontSize: 12,
  yAxisFontSize: 10,
  dataPointShape: ['diamond', 'circle', 'triangle', 'rect'],
  colors: ['#7cb5ec', '#f7a35c', '#434348', '#90ed7d', '#f15c80', '#8085e9'],
  pieChartLinePadding: 25,
  pieChartTextPadding: 15,
  titleColor: '#333333',
  titleFontSize: 18,
  subtitleColor: '#999999',
  subtitleFontSize: 15,
  toolTipColor: '#ffffff',
  toolTipPadding: 3,
  toolTipBackground: '#000000',
  toolTipOpacity: 0.95,
  toolTipLineHeight: 14,
  toolTipRadius: 3,
  radarGridCount: 3,
  radarLabelTextMargin: 15,
  isGradient: true, // 默认渐变色
};
